version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    expose:
      - 6379
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - ./opt/redis:/data
  next:
    restart: always
    image: 387911087127.dkr.ecr.ap-south-1.amazonaws.com/zee5-oeasis-dev:latest
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - .env.local